stages:
  - lint
  - test
  - dockerize
  - deploy

# Lint Job
lint:
  stage: lint
  image: python:3.9
  script:
    - echo "Installing dependencies for linting..."
    - pip install -r requirements.txt
    - pip install pylint
    - echo "Running linting..."
    - pylint *.py  # Adjust the directory to where your FastAPI code is
  allow_failure: true  # Fail the pipeline if linting fails

# Unit Test Job
unit_test:
  stage: test
  image: python:3.9
  script:
    - echo "Setting up environment..."
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Running unit tests..."
    - pytest unit_test.py
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour
  allow_failure: false  # Fail the pipeline if unit tests fail

# Integration Test Job
integration_test:
  stage: test
  image: python:3.9
  script:
    - echo "Setting up environment for integration tests..."
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Running integration tests..."
    - pytest integration_test.py  
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour
  allow_failure: false  

dockerize:
  stage: dockerize
  image: docker:20.10.23
  services:
    - docker:20.10.23-dind
  before_script:
    # Login to DockerHub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    # Build the Docker image
    - docker build -t $DOCKER_USERNAME/todo-app:latest .
    # Push the Docker image
    - docker push $DOCKER_USERNAME/todo-app:latest
  after_script:
    # Save Docker image digest
    - docker inspect $DOCKER_USERNAME/todo-app:latest --format='{{index .RepoDigests 0}}' > image-digest.txt || echo "No digest available"
  artifacts:
    paths:
      - image-digest.txt
    expire_in: 1 week
  only:
    - main 

# Deploy to EC2 Instance
eploy:
  stage: deploy
  image: appleboy/drone-ssh
  script:
    - echo "$EC2_SSH_PRIVATE_KEY" > devops.pem
    - chmod 600 devops.pem  
    - ssh -i "devops.pem" ec2-user@ec2-54-90-215-135.compute-1.amazonaws.com "docker pull rayen1/todo-app:latest && docker run -d -p 8000:80 rayen1/todo-app:latest"
  only:
    - main  # Deploy only from the main branch
  environment:
    name: production
    url: http://54.90.215.135
    
